version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: flower_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
volumes:
  mongo_data:
